### PR TITLE
Build on older Ubuntu for Centos 8 (glibc 2.28) compatibility

### PR DESCRIPTION
**Pull request by alippai**

### CODE REVIEW

**Comment by timvw** [comment]
Thank you for the contribution.

**Comment by timvw** [comment]
Launched a release cycle...

**Comment by alippai** [comment]
@timvw I see now that `ubuntu-latest` is referenced in other parts as well, won't that be a problem?

**Comment by timvw** [comment]
In those flows we're not building binaries (at least not for distribution) so I don't expect problems (yet :))

**Comment by timvw** [comment]
Binary builds are happening here: https://github.com/timvw/qv/actions/runs/2497084716 ...

**Comment by timvw** [comment]
Can you see the draft release? https://github.com/timvw/qv/releases/tag/untagged-a72fbf705f870e053ceb ?

**Comment by timvw** [comment]
I've downloaded the  qv-0.1.24-x86_64-unknown-linux-gnu-generic.tar.gz and seems to work on docker centos:8 image


[root@1d9bd41aa2f1 tmp]# tar -zxf qv-0.1.24-x86_64-unknown-linux-gnu-generic.tar.gz
[root@1d9bd41aa2f1 tmp]# ./qv
error: The following required arguments were not provided:
    <PATH>

USAGE:
    qv [OPTIONS] <PATH>

For more information try --help
[root@1d9bd41aa2f1 tmp]# ./qv --help
qv 0.1.24
Tim Van Wassenhove <tim@timvw.be>
quickly view your data

USAGE:
    qv [OPTIONS] <PATH>

ARGS:
    <PATH>    Location where the data is located

OPTIONS:
    -h, --help             Print help information
    -l, --limit <LIMIT>    Rows to return [default: 10]
    -q, --query <QUERY>    Query to execute [default: "select * from tbl"]
    -s, --schema           When provided the schema is shown
    -V, --version          Print version information
[root@1d9bd41aa2f1 tmp]# ld -version
GNU ld version 2.30-93.el8
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

**Comment by alippai** [comment]
> Can you see the draft release? [`untagged-a72fbf705f870e053ceb` (release)](https://github.com/timvw/qv/releases/tag/untagged-a72fbf705f870e053ceb) ?

The draft releases are not visible for me. Gives 404

**Pull request merged**
